modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Magersers/Creeper-Reversed/issues"
[[mods]]
modId="creeper_reversed"
version="1.0.0"
displayName="Creeper Reversed"
displayURL="https://github.com/Magersers/Creeper-Reversed"
logoFile="assets/creeper_reversed/icon.png"
authors="Magersers"
description='''The creeper stays calm. You hiss. You explode.'''
[[dependencies.creeper_reversed]]
modId="forge"
mandatory=true
versionRange="[47.4.0,48)"
ordering="NONE"
side="BOTH"
[[dependencies.creeper_reversed]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"